return {
  { 'K', vim.lsp.buf.hover, desc = 'Hover Documentation' },

  { "<leader>l", group = "LSP", icon = '󱁼' },
  { "<leader>lr", vim.lsp.buf.rename, desc = 'Rename', icon = '󰑕' },
  { "<leader>la", vim.lsp.buf.code_action, desc = 'Code Action' },
  { "<leader>lf", vim.lsp.buf.format, desc = 'Format Buffer' },
  { "<leader>lt", "<cmd>Trouble lsp_type_definitions toggle focus=false<cr>", desc = 'Type Definition', icon = '' },
  { "<leader>ls", "<cmd>Trouble symbols toggle focus=false<cr>", desc = 'Document Symbols', icon = '' },
  { "<leader>lS", "<cmd>Trouble symbols toggle pinned=true win.relative=win win.position=right win.size=0.2 <cr>", desc = 'Pin Document Symbols', icon = '' },
  { "<leader>lw", require('telescope.builtin').lsp_dynamic_workspace_symbols, desc = 'Workspace Symbols', icon = '' },
  { "<leader>li", '<cmd>lua vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())<cr>', desc = 'Toggle Inlay Hints' },
  { "<leader>lI", '<cmd>LspInfo<cr>', desc = 'LSP Info', icon = "" },
  { "<leader>lh", vim.lsp.buf.signature_help, desc = 'Signature Help', icon = "󰋖" },
  { "<leader>ld", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "Buffer Diagnostics" },
  { "<leader>lD", "<cmd>Trouble diagnostics toggle<cr>", desc = "Diagnostics", },

  { "<leader>xL", "<cmd>Trouble loclist toggle<cr>", desc = "Location List (Trouble)", },
  { "<leader>xQ", "<cmd>Trouble qflist toggle<cr>", desc = "Quickfix List (Trouble)", },

  { "<leader>ft", require('telescope.builtin').lsp_type_definitions, desc = 'Type Definition', icon = '' },
  { "<leader>fS", require('telescope.builtin').lsp_document_symbols, desc = 'Document Symbols', icon = '' },
  { "<leader>fd", require('telescope.builtin').diagnostics, desc = 'Diagnostics', icon = '' },
  { "<leader>fr", require('telescope.builtin').lsp_references, desc = 'Goto References' },
  { "<leader>fi", require('telescope.builtin').lsp_implementations, desc = 'Goto Implementation' },
  { "<leader>fw", require('telescope.builtin').lsp_dynamic_workspace_symbols, desc = 'Workspace Symbols', icon = '' },

  { "g", group = "Go To" },
  { "gd", vim.lsp.buf.definition, desc = 'Goto Definition' },
  { "gr", "<cmd>Trouble lsp toggle focus=true win.position=bottom<cr>", desc = 'Goto References' },
  { "gI", "<cmd>Trouble lsp_implementations toggle focus=true win.position=bottom<cr>", desc = 'Goto Implementation' },
  { "gD", vim.lsp.buf.declaration, desc = 'Goto Declaration' },
  { "gj", vim.diagnostic.goto_next, desc = 'Goto Next Diagnostic' },
  { "gk", vim.diagnostic.goto_prev, desc = 'Goto Prev Diagnostic' },
}
