return {
  { 'K',          vim.lsp.buf.hover,                                                                desc = 'Hover Documentation' },

  { "<leader>l",  group = "LSP" },
  { "<leader>lr", vim.lsp.buf.rename,                                                               desc = 'LSP Rename' },
  { "<leader>la", vim.lsp.buf.code_action,                                                          desc = 'Code Action' },
  { "<leader>lf", vim.lsp.buf.format,                                                               desc = 'Format Buffer' },
  { "<leader>lT", require('telescope.builtin').lsp_type_definitions,                                desc = 'Type Definition' },
  { "<leader>ls", require('telescope.builtin').lsp_document_symbols,                                desc = 'Document Symbols' },
  { "<leader>lw", require('telescope.builtin').lsp_dynamic_workspace_symbols,                       desc = 'Workspace Symbols' },
  { "<leader>li", '<cmd>lua vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())<cr>', desc = 'Toggle Inlay Hints' },
  { "<leader>lI", '<cmd>LspInfo<cr>',                                                               desc = 'LSP Info' },
  { "<leader>lh", vim.lsp.buf.signature_help,                                                       desc = 'Signature Documentation' },
  { "<leader>ld", vim.diagnostic.open_float,                                                        desc = 'Open Diagnostics' },
  { "<leader>lq", vim.diagnostic.setloclist,                                                        desc = 'Add Buffer Diagnostics to Quickfix' },
  { "<leader>lQ", vim.diagnostic.setqflist,                                                         desc = 'Add All Diagnostics to Quickfix' },

  { "<leader>g",  group = "Go To" },
  { "<leader>gd", vim.lsp.buf.definition,                                                           desc = 'Goto Definition' },
  { "<leader>gr", require('telescope.builtin').lsp_references,                                      desc = 'Goto References' },
  { "<leader>gI", require('telescope.builtin').lsp_implementations,                                 desc = 'Goto Implementation' },
  { "<leader>gD", vim.lsp.buf.declaration,                                                          desc = 'Goto Declaration' },
  { "<leader>gj", vim.diagnostic.goto_next,                                                         desc = 'Goto Next Diagnostic' },
  { "<leader>gk", vim.diagnostic.goto_prev,                                                         desc = 'Goto Prev Diagnostic' },
}
